/**
 * GENERATED by `scripts/gen-aborts.ts` from the usufruct Move source — do not edit.
 * Regenerate with `npm run codegen`. Every runtime abort constant (per module;
 * `#[test_only]` excluded), keyed on (module, code) — the abort's identity.
 */

/** One Move runtime abort: its module, code, and source constant name. */
export interface MoveAbortEntry {
  readonly module: string;
  readonly code: number;
  /** The Move constant, verbatim (e.g. `EAlreadyRetired`). */
  readonly name: string;
}

export const MOVE_ABORTS: readonly MoveAbortEntry[] = [
  { module: 'asset_state', code: 0, name: 'ENotRented' },
  { module: 'asset_state', code: 1, name: 'EInsufficientPayment' },
  { module: 'asset_state', code: 2, name: 'ERetireFlagBlocksBid' },
  { module: 'asset_state', code: 3, name: 'ERetiredNoBid' },
  { module: 'asset_state', code: 4, name: 'ERetireCommitmentFloorNotElapsed' },
  { module: 'asset_state', code: 5, name: 'EAlreadyRetired' },
  { module: 'asset_state', code: 6, name: 'EWrongEscrowUsufructCap' },
  { module: 'asset_state', code: 7, name: 'EPendingUsufructCap' },
  { module: 'asset_state', code: 8, name: 'EStaleUsufructCap' },
  { module: 'asset_state', code: 9, name: 'EUsufructCapNotStale' },
  { module: 'asset_state', code: 10, name: 'EReceiptEscrowMismatch' },
  { module: 'asset_state', code: 11, name: 'EWrongEscrowGovernanceCap' },
  { module: 'asset_state', code: 12, name: 'ENotRetired' },
  { module: 'asset_state', code: 13, name: 'ERetireAlreadyScheduled' },
  { module: 'asset_state', code: 14, name: 'ERetireCommitmentNotExtended' },
  { module: 'asset_state', code: 15, name: 'EReturnedDifferentAsset' },
  { module: 'asset_state', code: 16, name: 'EAlreadyRetiring' },
  { module: 'asset_state', code: 17, name: 'EUsufructCapStale' },
  { module: 'asset_state', code: 18, name: 'EEnsembleCommitmentFloorNotElapsed' },
  { module: 'asset_state', code: 19, name: 'EEnsembleCommitmentNotExtended' },
  { module: 'auction_window_policy', code: 0, name: 'EDescentCeilingZero' },
  { module: 'curve_shape_policy', code: 0, name: 'EAlphaNumRange' },
  { module: 'curve_shape_policy', code: 1, name: 'EAlphaDenRange' },
  { module: 'curve_shape_policy', code: 2, name: 'EDegenerateLinear' },
  { module: 'curve_shape_policy', code: 3, name: 'EAlphaAbsRange' },
  { module: 'ensemble_commitment_policy', code: 0, name: 'EEnsembleCommitmentFloorZero' },
  { module: 'escrow', code: 0, name: 'EAssetBorrowed' },
  { module: 'handover_policy', code: 0, name: 'EHandoverFloorZero' },
  { module: 'math', code: 0, name: 'EMulDivOverflow' },
  { module: 'math', code: 1, name: 'ENthRootBadDegree' },
  { module: 'monetary', code: 0, name: 'EPriceAddOverflow' },
  { module: 'policy_ensemble', code: 0, name: 'EHandoverFloorExceedsTenure' },
  { module: 'price_escalation_policy', code: 0, name: 'EDeltaZero' },
  { module: 'price_escalation_policy', code: 1, name: 'EBpsRange' },
  { module: 'rest_price_policy', code: 0, name: 'EPriceZero' },
  { module: 'retire_commitment_policy', code: 0, name: 'ERetireCommitmentFloorZero' },
  { module: 'tenure_duration_policy', code: 0, name: 'EDurationZero' },
  { module: 'tenure_extend_policy', code: 0, name: 'EMultiCycleNotAllowed' },
  { module: 'tenures', code: 0, name: 'ETenuresZero' },
];
