/**
 * Generate the abort registry from the Move source (drift-zero, like codegen).
 *
 * Extracts every runtime error constant — `const E<Name>: u64 = <code>;` that is
 * NOT `#[test_only]` — from each `usufruct::<module>`, and emits a committed TS
 * registry keyed on (module, code). The abort code alone is ambiguous (it is
 * per-module), so the pair is the identity. Run via `npm run codegen`.
 *
 * Source of truth: `$USUFRUCT_MOVE_PATH/sources/**` (default the sibling worktree),
 * the same package the type codegen reads.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = fileURLToPath(new URL('.', import.meta.url)); // packages/sdk/scripts/
const sdkRoot = join(here, '..'); // packages/sdk/ — same base as the codegen config
const movePath = process.env['USUFRUCT_MOVE_PATH'] ?? join(sdkRoot, '../../../../main/usufruct');
const sourcesDir = join(movePath, 'sources');
const outFile = join(here, '../src/highlevel/aborts.generated.ts');

/** Every `.move` under sources/, recursively. */
function moveFiles(dir: string): string[] {
  const out: string[] = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...moveFiles(p));
    else if (e.name.endsWith('.move')) out.push(p);
  }
  return out;
}

interface Abort {
  module: string;
  code: number;
  name: string;
}

const MODULE_RE = /^\s*module\s+usufruct::(\w+)\b/m;
// A runtime error constant: `const EName: u64 = N;` NOT prefixed `#[test_only]`.
const CONST_RE = /^\s*const\s+(E\w+)\s*:\s*u64\s*=\s*(\d+)\s*;/;

const aborts: Abort[] = [];
for (const file of moveFiles(sourcesDir)) {
  const src = readFileSync(file, 'utf8');
  const mod = MODULE_RE.exec(src)?.[1];
  if (!mod) continue;
  for (const line of src.split('\n')) {
    if (line.includes('#[test_only]')) continue; // never aborts at runtime
    const m = CONST_RE.exec(line);
    if (m) aborts.push({ module: mod, code: Number(m[2]), name: m[1]! });
  }
}

aborts.sort((a, b) => a.module.localeCompare(b.module) || a.code - b.code);

const body = aborts
  .map((a) => `  { module: '${a.module}', code: ${a.code}, name: '${a.name}' },`)
  .join('\n');

const out = `/**
 * GENERATED by \`scripts/gen-aborts.ts\` from the usufruct Move source — do not edit.
 * Regenerate with \`npm run codegen\`. Every runtime abort constant (per module;
 * \`#[test_only]\` excluded), keyed on (module, code) — the abort's identity.
 */

/** One Move runtime abort: its module, code, and source constant name. */
export interface MoveAbortEntry {
  readonly module: string;
  readonly code: number;
  /** The Move constant, verbatim (e.g. \`EAlreadyRetired\`). */
  readonly name: string;
}

export const MOVE_ABORTS: readonly MoveAbortEntry[] = [
${body}
];
`;

writeFileSync(outFile, out);
console.log(`gen-aborts: wrote ${aborts.length} aborts → ${relative(process.cwd(), outFile)}`);
